### ISSUE TITLE
What version of Rosetta is this know to work with?

### ISSUE THREAD

**Issue by Seanny123** [rifdock/rifdock#91]
Currently it says to use `bcov/stable1`. But if we don't have access to the Rosetta repository, would Rosetta `2019.35.60890` work?

**Comment by Seanny123** [comment]
It doesn't seem to work with Rosetta `20019.35.60890`. It gives the error:
```
/home/sean/git/rifdock/apps/rosetta/riflib/RotamerGenerator.cc: In function ‘core::pack::rotamer_set::RotamerSetOP devel::scheme::get_rosetta_rot_set(core::pose::Pose&, core::Size)’:
/home/sean/git/rifdock/apps/rosetta/riflib/RotamerGenerator.cc:363:84: error: cannot convert ‘const Residue’ {aka ‘const core::conformation::Residue’} to ‘const core::pose::Pose&’
  363 |  core::pack::rotamer_set::RotamerSetOP rotset( rsf.create_rotamer_set( pose.residue( ir ) ) );
      |                                                                        ~~~~~~~~~~~~^~~~~~
      |                                                                                    |
      |                                                                                    const Residue {aka const core::conformation::Residue}
In file included from /home/sean/git/rifdock/apps/rosetta/riflib/RotamerGenerator.cc:14:
/home/sean/src/rosetta_src_2019.35.60890_bundle/main/source/src/core/pack/rotamer_set/RotamerSetFactory.hh:43:67: note:   initializing argument 1 of ‘static core::pack::rotamer_set::RotamerSetOP core::pack::rotamer_set::RotamerSetFactory::create_rotamer_set(const core::pose::Pose&)’
   43 |  static RotamerSetOP create_rotamer_set( core::pose::Pose const & pose );
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/sean/git/rifdock/apps/rosetta/riflib/RotamerGenerator.cc: In function ‘void devel::scheme::get_acceptor_rays_lkball(const core::pose::Pose&, int, const devel::scheme::HBRayOpts&, std::vector<scheme::chemical::HBondRay>&, std::vector<std::pair<int, std::__cxx11::basic_string<char> > >&)’:
/home/sean/git/rifdock/apps/rosetta/riflib/RotamerGenerator.cc:1391:49: error: invalid types ‘double[int]’ for array subscript
 1391 |     for(int k = 0; k < 3; ++k) wat[k] = watxyz[k];
      |                                                 ^
make[3]: *** [apps/rosetta/riflib/CMakeFiles/riflib.dir/build.make:141: apps/rosetta/riflib/CMakeFiles/riflib.dir/RotamerGenerator.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:697: apps/rosetta/riflib/CMakeFiles/riflib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:569: apps/rosetta/CMakeFiles/rif_dock_test.dir/rule] Error 2
make: *** [Makefile:294: rif_dock_test] Error 2

```

**Comment by Seanny123** [comment]
Rosetta `2018.12.60119` also doesn't seem to work, but for different reasons:
```
In file included from /home/sean/git/rifdock/apps/rosetta/./riflib/rifdock_typedefs.hh:17,
                 from /home/sean/git/rifdock/apps/rosetta/./riflib/BurialManager.hh:14,
                 from /home/sean/git/rifdock/apps/rosetta/riflib/BurialManager.cc:3:
/home/sean/git/rifdock/schemelib/scheme/actor/BackboneActor.hh:7:10: fatal error: core/conformation/Residue.hh: No such file or directory
    7 | #include <core/conformation/Residue.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/sean/git/rifdock/apps/rosetta/./riflib/rifdock_typedefs.hh:17,
                 from /home/sean/git/rifdock/apps/rosetta/./riflib/DonorAcceptorCache.hh:14,
                 from /home/sean/git/rifdock/apps/rosetta/riflib/DonorAcceptorCache.cc:5:
/home/sean/git/rifdock/schemelib/scheme/actor/BackboneActor.hh:7:10: fatal error: core/conformation/Residue.hh: No such file or directory
    7 | #include <core/conformation/Residue.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [apps/rosetta/riflib/CMakeFiles/riflib.dir/build.make:63: apps/rosetta/riflib/CMakeFiles/riflib.dir/BurialManager.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [apps/rosetta/riflib/CMakeFiles/riflib.dir/build.make:76: apps/rosetta/riflib/CMakeFiles/riflib.dir/DonorAcceptorCache.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:697: apps/rosetta/riflib/CMakeFiles/riflib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:569: apps/rosetta/CMakeFiles/rif_dock_test.dir/rule] Error 2
make: *** [Makefile:294: rif_dock_test] Error 2
```

**Comment by bcov77** [comment]
I know this is years old. But it works with Rosetta 3.9.
